version: "3.8"


services:
  producer:
    container_name: producer
    build:
      context: ./producer
      dockerfile: Dockerfile
    networks:
      - tutor_local_default
    env_file:
      - ./producer/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started


  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
      - tutor_local_default
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    entrypoint: >
      /bin/bash -c "
      rabbitmq-server &
      sleep 10 &&
      rabbitmqctl add_vhost my_vhost &&
      rabbitmqctl set_permissions -p my_vhost admin '.*' '.*' '.*' &&
      rabbitmqctl set_permissions -p / admin '.*' '.*' '.*' &&
      rabbitmqctl stop_app &&
      rabbitmqctl start_app &&
      wait
      "
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    container_name: minio
    networks:
      - tutor_local_default
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio-data:/data



volumes:
  rabbitmq_data:
    driver: local

networks:
  tutor_local_default:
    external: True

