version: "3.8"


services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    networks:
      - tutor_local_default
    env_file:
      - ./producer/.env
    depends_on:
      - rabbitmq
      - minio

  rabbitmq:
    image: rabbitmq:3.10.7-management
    networks:
      - tutor_local_default
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - .env

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    networks:
      - tutor_local_default
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio-data:/data


networks:
  tutor_local_default:
    external: True

