"""deleted_file_url

Revision ID: 17e5987c8f31
Revises: 95991f710048
Create Date: 2025-01-10 00:00:10.326411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17e5987c8f31"
down_revision: Union[str, None] = "95991f710048"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
