"""cascade_delete_card_fix

Revision ID: 1fa760ac1572
Revises: c690dcd96109
Create Date: 2025-03-26 17:53:16.624995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1fa760ac1572"
down_revision: Union[str, None] = "c690dcd96109"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("cards_file_id_fkey", "cards", type_="foreignkey")
    op.create_foreign_key(
        None, "cards", "files", ["file_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cards", type_="foreignkey")
    op.create_foreign_key(
        "cards_file_id_fkey",
        "cards",
        "files",
        ["file_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
