"""sharing

Revision ID: 246a430b12bb
Revises: b357fdc45de7
Create Date: 2025-01-29 23:46:33.254366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "246a430b12bb"
down_revision: Union[str, None] = "b357fdc45de7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sharing_urls",
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_sharing_urls_card_id"),
        "sharing_urls",
        ["card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sharing_urls_code"), "sharing_urls", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_sharing_urls_user_id"),
        "sharing_urls",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sharing_urls_user_id"), table_name="sharing_urls")
    op.drop_index(op.f("ix_sharing_urls_code"), table_name="sharing_urls")
    op.drop_index(op.f("ix_sharing_urls_card_id"), table_name="sharing_urls")
    op.drop_table("sharing_urls")
    # ### end Alembic commands ###
