"""added_card_type_translation

Revision ID: 275e482cef90
Revises: e5ad6b75e7c0
Create Date: 2025-01-18 16:57:23.505515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "275e482cef90"
down_revision: Union[str, None] = "e5ad6b75e7c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cards", sa.Column("card_type_translation", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "card_type_translation")
    # ### end Alembic commands ###
