"""fix

Revision ID: 3639cea269f2
Revises: 150c64776b2c
Create Date: 2025-02-05 02:16:40.902379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3639cea269f2"
down_revision: Union[str, None] = "150c64776b2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("fki_cards_author_id_fkey", table_name="cards")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "fki_cards_author_id_fkey", "cards", ["author_id"], unique=False
    )
    # ### end Alembic commands ###
