"""file_uploaded_by_user

Revision ID: 36a2f076366a
Revises: 12e1f36024f2
Create Date: 2025-03-02 21:57:09.255162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36a2f076366a"
down_revision: Union[str, None] = "12e1f36024f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column("uploaded_by_user", sa.Boolean(), nullable=True)
    )

    op.execute("UPDATE files SET uploaded_by_user = FALSE")

    op.alter_column(
        "files",
        "uploaded_by_user",
        nullable=False
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "uploaded_by_user")
    # ### end Alembic commands ###
