"""added_markdown

Revision ID: 4dbbe14e959a
Revises: 17e5987c8f31
Create Date: 2025-01-10 17:26:04.014177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4dbbe14e959a"
down_revision: Union[str, None] = "17e5987c8f31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cards", sa.Column("markdown_text", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "markdown_text")
    # ### end Alembic commands ###
