"""nullable_file_id

Revision ID: b357fdc45de7
Revises: bc0954869357
Create Date: 2025-01-29 18:19:05.663258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b357fdc45de7"
down_revision: Union[str, None] = "bc0954869357"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cards", "file_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cards", "file_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
