"""admin_public_files

Revision ID: bc0954869357
Revises: c032d2627323
Create Date: 2025-01-28 01:45:04.903819

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc0954869357"
down_revision: Union[str, None] = "c032d2627323"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column(
            "description", sa.String(), server_default="", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "description")
    # ### end Alembic commands ###
