"""file_template_for_column

Revision ID: c690dcd96109
Revises: 36a2f076366a
Create Date: 2025-03-17 21:56:22.346249

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c690dcd96109"
down_revision: Union[str, None] = "36a2f076366a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files", sa.Column("template_for", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "template_for")
    # ### end Alembic commands ###
