"""cascade_delete

Revision ID: e5ad6b75e7c0
Revises: 4dbbe14e959a
Create Date: 2025-01-11 17:31:13.589624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5ad6b75e7c0"
down_revision: Union[str, None] = "4dbbe14e959a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("cards_file_id_fkey", "cards", type_="foreignkey")
    op.create_foreign_key(
        None, "cards", "files", ["file_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cards", type_="foreignkey")
    op.create_foreign_key(
        "cards_file_id_fkey", "cards", "files", ["file_id"], ["id"]
    )
    # ### end Alembic commands ###
